/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Facade;

import Asteroid.Main.AsteroidGame;
import Snail.SnailGame;
import Snake.SnakeGame;
import Tetris.Tetris;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author KelvinOjeda
 */
public class CheckFacade extends javax.swing.JFrame {

    /**
     * Creates new form CheckFacade
     */
    private AsteroidGame asteroidGame;
    private SnailGame snailGame;
    private SnakeGame snakeGame;
    private Tetris tetris;
    public CheckFacade() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBAsteroidGame = new javax.swing.JButton();
        jBSnailGame = new javax.swing.JButton();
        jBTetrisGame = new javax.swing.JButton();
        jBSnakeGame = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBAsteroidGame.setFont(new java.awt.Font("Dank Mono", 0, 18)); // NOI18N
        jBAsteroidGame.setText("Asteroid Game");
        jBAsteroidGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAsteroidGameActionPerformed(evt);
            }
        });

        jBSnailGame.setFont(new java.awt.Font("Dank Mono", 0, 18)); // NOI18N
        jBSnailGame.setText("Snail Game");
        jBSnailGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSnailGameActionPerformed(evt);
            }
        });

        jBTetrisGame.setFont(new java.awt.Font("Dank Mono", 0, 18)); // NOI18N
        jBTetrisGame.setText("Tetris Game");
        jBTetrisGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTetrisGameActionPerformed(evt);
            }
        });

        jBSnakeGame.setFont(new java.awt.Font("Dank Mono", 0, 18)); // NOI18N
        jBSnakeGame.setText("Snake Game");
        jBSnakeGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSnakeGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jBAsteroidGame)
                .addGap(26, 26, 26)
                .addComponent(jBSnailGame)
                .addGap(26, 26, 26)
                .addComponent(jBTetrisGame)
                .addGap(18, 18, 18)
                .addComponent(jBSnakeGame)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAsteroidGame, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBSnailGame, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBTetrisGame, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBSnakeGame, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(184, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAsteroidGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAsteroidGameActionPerformed
        asteroidGame= new AsteroidGame();
        asteroidGame.showWindow();
    }//GEN-LAST:event_jBAsteroidGameActionPerformed

    private void jBSnakeGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSnakeGameActionPerformed
        snakeGame= new SnakeGame();
        snakeGame.startGame();
    }//GEN-LAST:event_jBSnakeGameActionPerformed

    private void jBSnailGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSnailGameActionPerformed
        
       snailGame= new SnailGame(true);
        
        try {
            snailGame.iniciarJuego();
        } catch (InterruptedException ex) {
            Logger.getLogger(CheckFacade.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(CheckFacade.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jBSnailGameActionPerformed

    private void jBTetrisGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTetrisGameActionPerformed
        tetris= new Tetris();
        tetris.setVisible(true);
    }//GEN-LAST:event_jBTetrisGameActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckFacade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckFacade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckFacade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckFacade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckFacade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAsteroidGame;
    private javax.swing.JButton jBSnailGame;
    private javax.swing.JButton jBSnakeGame;
    private javax.swing.JButton jBTetrisGame;
    // End of variables declaration//GEN-END:variables
}
